### ISSUE TITLE
Shard infinite loop v0.9.0

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/shards#301] opened 2019-10-14 03:41 UTC
```
dependencies:
  action-controller:
    github: spider-gazelle/action-controller
    version: "~> 1.8.0"
  jennifer:
    github: imdrasil/jennifer.cr
```

**Comment by straight-shoota** [comment] 2019-10-14 06:58
Could you please provide more details on this issue? Might be a duplicate of #282

**Comment by ysbaddaden** [comment] 2019-10-14 08:42
Duplicate of #282. No infinite loop. It will complete. In fact it completes in 35s. Add a version constraint for jennifer like `version: ~> 0.8.0` and it completes in 0.3s.

**Closed by ysbaddaden** 2019-10-14 08:42 UTC
