### ISSUE TITLE
Caching Shards?

### ISSUE THREAD

**Issue by Kentoseth** [crystal-lang/shards#181] opened 2017-10-30 19:00 UTC
I am copy/pasting this issue from Amber - [here](https://github.com/amberframework/amber/issues/341)

As this is an issue with shards and not amber.

### Description

Is it possible to cache the shards and then share those saved packages across different projects (when creating a new project)?

Currently when I attempt to create 2 or 3 different projects, it is re-downloading the same shards each time, whereas I already have them all downloaded locally.

If this doesn't exist already, it can be considered a `feature`

### Steps to Reproduce

1. `amber new blog1`
2. Now in an alternative directory: `amber new blog2`
3. I tried to copy/paste both `lib/` and `.shards/` each to a new project, but when running `shards install` it still re-downloads the shards.
4. I also tried to create a project within an existing-project (assuming `shards` would be fetched upstream), but it still downloads the `shards`

**Expected behavior:** [What you expect to happen]

It should be possible to cache and share packages across projects (or cache the projects at a higher level and let different projects fetch from the cache first)

**Actual behavior:** [What actually happens]

Shards are downloaded repeatedly.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

You can get this information from copy and pasting the output of `amber --version` and `amber --version` from the command line. Also, please include the OS and what version of the OS you're running.

Amber CMD (amberframework.org) - v0.3.0
Crystal 0.23.1

**Comment by ysbaddaden** [comment] 2017-10-31 16:53
Duplicate of #180.

Also, shards are already cached, but locally to a project, and only reinstalled when it's needed.

**Closed by ysbaddaden** 2017-10-31 16:53 UTC

**Comment by Kentoseth** [comment] 2017-10-31 19:32
@ysbaddaden is it possible for me to copy shards from 1 project to another? I am using the same shards for amber projects repeatedly.

**Comment by ysbaddaden** [comment] 2017-11-02 15:47
Yes. That would avoid full clones, but won't prevent running "git fetch" to make sure we have up to date repository versions.

**Comment by Kentoseth** [comment] 2017-11-03 18:42
@ysbaddaden 

which folders must I copy specifically?

`.shards/
&&
`lib/`

?

**Comment by ysbaddaden** [comment] 2017-11-06 08:17
`.shards` will suffice. It contains the full Git clones. The `lib` folder will be populated from them.
