### ISSUE TITLE
shards install --production doesn't use `.lock`?

### ISSUE THREAD

**Issue by KCErb** [crystal-lang/shards#290] opened 2019-08-07 05:34 UTC
Hi there,

Here's an example of what I'm talking about:
https://github.com/KCErb/shards_test

It has two shards: `mylib` and `foobar`. `mylib` depends on `foobar` via

```
dependencies:
  foobar:
    path: ../foobar
    version: "~> 0.1"
```

if I `shards install` I get a `shard.lock` locking this down to `0.1.0`. So far so good.

Now, if I update `foobar/shard.yml` to be version `0.1.1` and then run `shards install` in `mylib` I get an error:

```
$ shards install
Resolving dependencies
Outdated shard.lock (foobar requirements changed). Please run shards update instead.
```

I'm not sure I love / understand this but it's fine. I did expect that using `--production` would be the answer though. I expected that `--production` means: don't break my build, just pull the repo in the lock and move on. However:

```
$ shards install --production --verbose
Resolving dependencies
Outdated shard.lock (foobar requirements changed). Please run shards update instead.
```

I noticed I was getting this on `crystal 0.29 => shards 0.8.1` so I updated to get latest shards `0.9.0` but no difference in behavior between them.

**Comment by ysbaddaden** [comment] 2019-08-07 06:46
Shards always uses `shard.yml`. If your lock is inconsistent with your spec, Shards bails out. Production won't overlook the inconsistency.

**Comment by KCErb** [comment] 2019-08-07 08:38
Hmm, the desired outcome here is reproducibility. Is there some way with shards to be able to put up a `shard.yml`, generate a `shard.lock` and from then on, in that repo some `shards` command will be guaranteed to just go pull down the libraries without complaint? I assumed the lock's job was to make that possible.

If I understand you correctly, the answer is no. At any given time, `shards install` can fail if a dependency somewhere in your tree updates, even if it's indirect (as was my case when the Docker build of my `lucky` project failed because my version of `lucky` depends on  `avram:0.10.0` which has [an unspecified dependency](https://github.com/luckyframework/avram/blob/v0.10.0/shard.yml#L19-L20) on `crystal-db` which pushed a minor version bump  5 days ago).

Do I understand correctly or am I missing something? Thanks in advance for your help :)

**Comment by ysbaddaden** [comment] 2019-08-07 14:35
Please send a reproducible minimal shard.yml and shard.lock.

Reproducible installs is somewhat impossible with a path dependency. Shards must take the dependency at the given path, with no alternative. If the shard.yml of that path dependency changes, Shards will break just as if you changed the local shard.yml (I.e. you updated the dependency, and thus have to use shards update to update the lock). There is nothing we can do to fix that.

**Comment by KCErb** [comment] 2019-08-07 15:32
I didn't really mean for the issue to be about `path` dependencies. My real-life example is with normal remote dependencies.

So I went ahead and created
https://github.com/KCErb/shards-test-foobar
https://github.com/KCErb/shards-test-mylib

There are two releases of foobar (0.1.0 and 0.1.1), and mylib has `0.1.0` in its lock. 

Running `shards install` in `mylib` when it already has `foobar:0.1.0` gives me no error. 

So

1. I'll reply back here if/when I can reproduce (I suspect it something to do with the indirection or the lack of a version specification in avram)

2. I'm confused that after updating foobar to 0.1.1 and running `shards install` again in `mylib` I got the following:

```
$ shards install --verbose
git ls-remote --get-url origin
Fetching https://github.com/KCErb/shards-test-foobar.git
git fetch --all --quiet
git tag --list --column=never
versions: 0.1.1, 0.1.0
git ls-tree -r --full-tree --name-only v0.1.1 -- shard.yml
git show v0.1.1:shard.yml
git ls-tree -r --full-tree --name-only v0.1.1 -- shard.yml
git show v0.1.1:shard.yml
git ls-tree -r --full-tree --name-only v0.1.1 -- shard.yml
git show v0.1.1:shard.yml
Using shards-test-foobar (0.1.1)
```

but if I look in `shards-test-mylib/lib/shards-test-foobar/shard.yml` I see `version: 0.1.0` meaning it didn't actually update. I don't want to get off on a tangent here, but is that expected behavior?

The only way I know for sure to help someone else reproduce is to have them clone, and then me bump the version on remote, and then have them run `shards install` again.

**Comment by bcardiff** [comment] 2019-08-07 18:28
I have another example that might offer some information
* https://github.com/bcardiff/sample-crystal-ci/blob/master/shard.yml has only the github repo
* https://github.com/bcardiff/sample-crystal-ci/blob/master/shard.lock has a specific tag information
* https://circleci.com/gh/bcardiff/sample-crystal-ci/359 in the ci running shards (install) is trying to install a newer tag of the crystal-mysql

**Comment by paulcsmith** [comment] 2019-08-07 18:30
This sounds like what I was running into as well. For some reason on shards 0.8 it was trying to install a newer version of the dependency than was in the shard.yml or shard.lock and was telling me to run shards update. It worked fine locally when using shards 0.9

I would upgrade to 0.8 but for some reason the heroku build pack is still using 0.8. I'll try to add an example here soon, but pretty busy with a new Lucky release

**Comment by KCErb** [comment] 2019-08-07 18:33
@bcardiff thanks for putting that together! That's exactly what I was trying to demonstrate, didn't think to use CircleCI for the demo. Perfect!

**Comment by ysbaddaden** [comment] 2019-08-08 07:22
Don't trust the resolver of Shards 0.8 and below: it's crap and has always said it was.

The new resolver from Shards 0.9 onwards should be correct (but has a memory/time issue that is hard to fix).

**Comment by ysbaddaden** [comment] 2019-08-08 07:28
If it happens with 0.9, please create an integration test that reproduces the bug. I'll look at it when I have some time.

If it happens on 0.8 only, please close. I won't fix it.

**Comment by paulcsmith** [comment] 2019-08-08 14:32
Good to know, thanks @ysbaddaden. I think that it is only on 0.8.0. Is that correct @KCErb? If you have 0.9 does it work?

**Comment by KCErb** [comment] 2019-08-08 20:27
Hmm I'm still having trouble reproducing the 0.8 error with my little cadre of repos. So I don't feel confident that I understand it well enough to isolate. Tomorrow I'll rebuild the actual project for crystal 0.30 and thus get shards 0.9 and report back here. Thanks all!

**Comment by ysbaddaden** [comment] 2019-08-08 23:59
Shards 0.9 isn't distributed with crystal for the time being, which is probably a goid idea because of #282.

**Closed** 2019-08-09 00:04 UTC
