### ISSUE TITLE
strange error when branch not found

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#128] opened 2016-09-27 20:50 UTC
```
dependencies:
  myhtml:
    github: kostya/myhtml
    branch: data
```

crystal deps

```
Updating https://github.com/kostya/myhtml.git
git command failed: git tag --list --contains data --column=never (malformed object name data). Maybe you didn't install git?
```

i think it should be more human

**Comment by ysbaddaden** [comment] 2016-09-28 08:04
This is a duplicate of #108 that I must fix by:

1. testing for `git` availability and failing with "git not found";
2. adding contextual error messages when a git command fails.

**Closed** 2016-09-28 12:43 UTC
Labels: bug, enhancement
