### ISSUE TITLE
Will shards.lock be respected in a dependency

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/shards#281] opened 2019-06-15 00:45 UTC
If I have a dependency eg.
```yaml
shards:
  yolo:
    github: wontruefree/yolo.cr
```

and that dependency has a `shards.lock` file.  Will shards used that lock file when resolving dependencies?

**Comment by ysbaddaden** [comment] 2019-06-15 07:21
No. `shard.yml` is the only source for resolving dependencies. The lock file is meant for reproducible installs across computers (when directly working on an app or library).

**Closed by ysbaddaden** 2019-06-15 07:21 UTC

**Comment by straight-shoota** [comment] 2019-06-15 07:34
To further clarify: Shards that are used libraries generally shouldn't have a `shard.lock` file anyway because they don't need reproducible installs.

That's why `crystal init` adds `shard.lock` to the gitignore file for libraries.

**Comment by wontruefree** [comment] 2019-06-15 19:20
I was watching a talk where npm is trying to use lockfiles to reduce dependency resolution. I am not sure if this is because of some things in their ecosystem or something technically.  But I was curious if we could do that here.

**Comment by ysbaddaden** [comment] 2019-06-15 19:43
NPM doesn't even try to resolve dependencies. It installs whatever a dependency requires, recursively, installing the same dependencies over and over at the same of at different versions. In that very specific use case, it should indeed respect the lockfile of nested dependencies.

Now, a dependency manager that does resolve dependencies for a project (i.e. anything but NPM) will resolve dependencies globally, taking into account the whole dependency graph, and respecting some constraints, such as "can't install a dependency twice". In that case, we can never respect lock files of nested dependencies. Doing so would lead to never be able to find a satisfiable solution.

**Comment by wontruefree** [comment] 2019-06-17 16:55
Thanks that makes a lot of sense.  And, explains why they are moving in that direction.
