### ISSUE TITLE
build --release error

### ISSUE THREAD

**Issue by etm** [crystal-lang/shards#171] opened 2017-08-29 17:24 UTC
[eTM@heart ~]$ crystal -v
Crystal 0.23.1 [e2a1389e8] (2017-07-13) LLVM 3.8.1
[mangler@heart ~]$ cat test.cr
module Helper
  macro named(var)
    def {{ var.id }}
     @{{ var.id }} ||= 1
    end
  end
end

class Assistant
  include Helper

  named test
end

puts Assistant.new.test
[eTM@heart ~]$ crystal test.cr 
1
[eTM@heart ~]$ crystal build test.cr 
[eTM@heart ~]$ ./test
1
[eTM@heart ~]$ crystal build --release test.cr 
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102: 12153 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"

**Comment by Sija** [comment] 2017-08-29 18:03
Wrong repo, also duplicate of https://github.com/crystal-lang/crystal/issues/4719.

**Closed** 2017-08-29 18:24 UTC
