### ISSUE TITLE
shards tag command

### ISSUE THREAD

**Issue by repomaa** [crystal-lang/shards#345] opened 2020-04-06 15:14 UTC
It'd be helpful to have somekind of `shards tag` command which would check for dirty git tree and if everything is fine add a git tag with the version specified in shard.yml. If using it would be established i believe much less problems of the sort https://github.com/crystal-lang/shards/pull/341 would be encountered. Maybe even provide a way to bump versions like the `npm version` command, which would set the version in shard.yml, commit and add a git tag.

**Comment by straight-shoota** [comment] 2020-04-06 15:37
Duplicate of #98

Also related: #29

**Closed by straight-shoota** 2020-04-06 15:37 UTC

**Comment by repomaa** [comment] 2020-04-07 00:19
Hm I agree that #98 is related, but I see this tag subcommand as a subset of what #98 would do. This wouldn’t assume anything about how you publish a shard (which I believe was your issue with #98, and I agree)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by straight-shoota** [comment] 2020-04-07 00:27
Sure, with a more limited functionality, it sounds more feasible 👍 I'd still suggest to continue the discussion there, because it's still the same feature, just with a more focused scope of operation.
Also `shards tag` doesn't seem like a fitting name when you actually want to do a release.
