### ISSUE TITLE
crystal deps --production not updated shards now

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#141] opened 2016-11-24 14:05 UTC
i update shard kemal, file shards.lock changed, i commit it, and deploy. (on the server it builded in shared path, i just copy shards.yml, shards.lock to it, from current release and ` crystal deps --production`)

and it works fine, but now code of the shard in the lib, not updated to actual, so it compiled with 0.17.0

diff was
```diff
   kemal:
     github: sdogruyol/kemal
-    version: 0.17.0
+    version: 0.17.1
```

versions in shards.lock now not synced with lib dir, with `crystal deps` command

**Comment by ysbaddaden** [comment] 2016-11-24 14:59
Do you still have the legacy `libs` folder on your server? There is a now issue with Crystal 0.20.0's `CRYSTAL_PATH` where the legacy `libs` takes precedence over `lib`. Be sure to delete the `libs` directory, otherwise Crystal will keep using the old library. See #140.

**Comment by kostya** [comment] 2016-11-24 15:00
no, libs removed, code not updated in lib.

**Comment by kostya** [comment] 2016-11-24 15:14
easy to reproduce:
```
crystal init app bla
cd bla
printf "\ndependencies:\n  kemal:\n    github: sdogruyol/kemal\n    version: 0.17.0\n" >> shard.yml
crystal deps
cd ..
cp -r bla bla2
cd bla
sed -i -e 's/0.17.0/0.17.1/g' shard.yml
crystal deps update
cd ..
cd bla2
cp ../bla/shard* ./
crystal deps --production
cd ..
diff bla/lib/kemal/src/kemal/context.cr bla2/lib/kemal/src/kemal/context.cr
```

```diff
12,16c12
<       @params ||= if @request.param_parser
<                     @request.param_parser.not_nil!
<                   else
<                     Kemal::ParamParser.new(@request)
<                   end
---
>       @params ||= Kemal::ParamParser.new(@request)
```

works in previous version

**Comment by ysbaddaden** [comment] 2016-11-24 15:54
Duplicate of #107

**Closed** 2016-11-24 15:53 UTC
